blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^boards/', include('boards.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

boards/urls.py
from django.conf.urls import url
from boards import views

app_name = 'boards'
urlpatterns = [
    # url(r'^$', views.BoardsView.as_view(), name='index'),
    url(r'^$', views.BoardsView.as_view(), name='index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.BoardDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.BoardDetail.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/new/$', views.NewTopic.as_view(), name='new_topic')
    url(r'^(?P<pk>[0-9]+)/new/$', views.new_topic, name='new_topic'),
    url(r'^(?P<pk>[0-9]+)/topic/(?P<topic_pk>\d+)$', views.topic_posts, name='topic_posts'),
    url(r'^(?P<pk>[0-9]+)/topic/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
]

boards/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator
# Create your models here.


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_post_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='post')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

boards/forms.py
from django import forms
from .models import Topic, Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

boards/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.http import HttpResponseBadRequest, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from boards.models import Board, Topic, Post
from django.contrib.auth.models import User
from .forms import NewTopicForm, PostForm
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
import pdb


class BoardsView(generic.ListView):
    template_name = 'boards/index.html'
    context_object_name = 'boards'
    model = Board


def home(request):
    boards = Board.objects.all()
    return render(request, 'boards/index.html', {'boards': boards})


class BoardDetail(generic.ListView):
    model = Topic
    template_name = 'boards/detail.html'
    context_object_name = 'topics'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super(BoardDetail, self).get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset


def board_topics(request, pk):
    # try:
    #     board = Board.objects.get(pk=pk)
    # except Board.DoesNotExist:
    #     raise Http404
    board = get_object_or_404(Board, pk=pk)
    queryset = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 5)
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        topics = paginator.page(1)
    except EmptyPage:
        topics = paginator.page(paginator.num_pages)

    return render(request, 'boards/detail.html', {'board': board, 'topics': topics})


class NewTopic(generic.DetailView):
    model = Board
    template_name = 'boards/new_topic.html'

    def post(self, request, **kwargs):
        # pdb.set_trace()
        pk = kwargs.get('pk')
        board = get_object_or_404(Board, pk=pk)
        user = User.objects.first()
        form = NewTopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', pk=board.pk)
        else:
            return render(request, 'boards/new_topic.html', {
                'board': board,
                'error_message': "Invalid"
            })
        # try:
        #     subject = request.POST['subject']
        #     message = request.POST['message']
        #
        #     topic = Topic.objects.create(
        #         subject=subject,
        #         board=board,
        #         starter=user
        #     )
        #
        #     post = Post.objects.create(
        #         message=message,
        #         created_by=user,
        #         topic=topic
        #     )
        # except KeyError as e:
        #     return render(request, 'boards/new_topic.html', {
        #         'board': board,
        #         'error_message': "Missing POST parameters {}".format(e)
        #     })
        #
        # return redirect('boards:detail', pk=board.pk)


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            return redirect('boards:topic_posts', pk=board.pk, topic_pk=topic.pk)
    else:
        form = NewTopicForm()

    return render(request, 'boards/new_topic.html', {'form': form, 'board': board})


@login_required
def topic_posts(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    topic.views += 1
    topic.save()
    return render(request, 'boards/topic_posts.html', {'topic': topic})


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('boards:topic_posts', pk=pk, topic_pk=topic_pk)
    else:
        form = PostForm()

    return render(request, 'boards/reply_topic.html', {'form': form, 'topic': topic})


@method_decorator(login_required, name='dispatch')
class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'boards/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super(PostUpdateView, self).get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()

        return redirect('boards:topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

templates/boards/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Board</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">
            New Topic
        </a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Topic</th>
            <th>Starter</th>
            <th>Replies</th>
            <th>Views</th>
            <th>Last Update</th>
        </tr>
        </thead>
        <tbody>
        {% for topic in topics %}
            <tr>
                <td><a href="{% url 'boards:topic_posts' board.pk topic.pk %}">{{ topic.subject }}</a></td>
                <td>{{ topic.starter.username }}</td>
                <td>{{ topic.replies }}</td>
                <td>{{ topic.views }}</td>
                <td>{{ topic.last_updated }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'includes/pagination.html' %}
{% endblock %}

templates/boards/edit_post.html
{%extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:detail' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
    <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
    </form>
{% endblock %}

templates/boards/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
    {% if boards %}
        <div class="row">
            <div class="col-12 mt-2">
                <table class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>Board</th>
                            <th>Posts</th>
                            <th>Topics</th>
                            <th>Last Post</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for board in boards %}
                            <tr>
                                <td>
                                    <a href="{% url 'boards:detail' board.pk %}">
                                        {{ board.name }}
                                    </a>
                                    <small class="text-muted d-block">{{ board.description }}</small>
                                </td>
                                <td>{{ board.get_post_count }}</td>
                                <td>{{ board.topics.count }}</td>
                                <td>
                                    {% with post=board.get_last_post %}
                                        {% if post %}
                                            <small>
                                                <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                                                    By {{ post.created_by.username }} at {{ post.created_at }} pk {{ board.pk  }} topic_pk {{ post.topic.pk }}
                                                </a>
                                            </small>
                                        {% else %}
                                            <small class="text-muted">
                                              <em>No posts yet.</em>
                                            </small>
                                        {% endif %}

                                    {% endwith %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/boards/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
    Start a new topic
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Board</a></li>
    <li class="breadcrumb-item "><a href="{% url 'boards:detail' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New Topic</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post</button>
    </form>
{%  endblock %}

templates/boards/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post a reply{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:detail' topic.board.pk %}">{{ topic.board.name }}</a></li>
{#    <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>#}
    <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}

    <form method="post" class="mb-4">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post a reply</button>
    </form>

    {% for post in topic.posts.all %}
        <div class="card mb-2">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at }}</small>
                    </div>
                </div>
                {{ post.message }}
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/boards/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ topic.subject }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:detail' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'boards:reply_topic' pk=topic.board.pk topic_pk=topic.pk %}" class="btn btn-primary" role="button">Reply</a>
    </div>
    {% for post in topic.posts.all %}
        <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
            {% if forloop.first %}
                <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
            {% endif %}
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{% static 'img/avatar.svg' %}" alt="{{ post.created_by.username }}" class="img-thumbnail" style="height: 100px">
                        <small>Posts: {{ post.created_by.posts.count }}</small>
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.message }}
                        {% if post.created_by == user %}
                            <div class="mt-3">
                                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.pk post.pk %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}