accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
import views

app_name = 'accounts'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^boards/', include('boards.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

boards/urls.py
from django.conf.urls import url
from boards import views

app_name = 'boards'
urlpatterns = [
    # url(r'^$', views.BoardsView.as_view(), name='index'),
    url(r'^$', views.BoardsView.as_view(), name='index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.BoardDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.BoardDetail.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/new/$', views.NewTopic.as_view(), name='new_topic')
    url(r'^(?P<pk>[0-9]+)/new/$', views.new_topic, name='new_topic'),
    url(r'^(?P<pk>[0-9]+)/topic/(?P<topic_pk>\d+)$', views.topic_posts, name='topic_posts'),
    url(r'^(?P<pk>[0-9]+)/topic/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
]

templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load bootstrap4 %}
{% block bootstrap4_extra_head %}
    <title>
        {% block title %}
            Django Boards
        {% endblock %}
    </title>
    {% block stylesheet_head %}{% endblock %}
{% endblock %}

{% block bootstrap4_content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'boards:index' %}" class="navbar-brand">Boards</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a href="#" class="dropdown-item">My Account</a>
                            <a href="{% url 'accounts:password_change' %}" class="dropdown-item">Change Password</a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'accounts:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </li>
                </ul>
                {% else %}
                    <form action="" class="form-inline ml-auto">
                        <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log In</a>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign Up</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% block breadcrumb %}
                {% endblock %}
            </ol>
        </nav>
        {% block content %}(no content){% endblock %}
    </div>
{% endblock %}

templates/base_accounts.html
{% extends 'base.html' %}

{% load  static %}
{% block stylesheet_head %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block bootstrap4_content %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'boards:index' %}">Django Boards</a>
        </h1>
        {% block content %}{% endblock %}
    </div>
{% endblock %}